### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by rajneeshm49** [cornflourblue/angular2-animation-tutorial-example#1]
Hello,
My node version is 7.10.0 and npm version is 5.0.3
I cloned the repository and inside root folder I ran npm install and npm start.
After that it gives me below error:

node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
node_modules/rxjs/observable/dom/WebSocketSubject.d.ts(24,22): error TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular2-animation-tutorial-example@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-animation-tutorial-example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by codebubb** [comment]
Hi @rajneeshm49,

There's an issue with the rxjs extensions working with TypeScript 2.4.1 (see https://github.com/ReactiveX/rxjs/issues/2699)

Simple fix for it is to set the dependency for TypeScript to 2.4.0 or lower in your package.json.  For example:

```
"devDependencies": {
        "@types/node": "^6.0.60",
        "concurrently": "^3.1.0",
        "lite-server": "^2.3.0",
        "typescript": "2.4.0"
    }
```

I was able to ```npm start``` after this.  Hope that helps.

**Comment by cornflourblue** [comment]
This has been fixed in RxJS 5.4.2 so no need for a workaround anymore - https://github.com/Microsoft/TypeScript/issues/16593#issuecomment-313389674
